// The permission catalog: every capability CompassDocs guards, as data.
//
// Code-defined rather than a table, for three reasons: a permission cannot be
// orphaned by a half-applied migration, the set is diffable in review, and the
// literal-union PermissionKey below makes a typo in can("documnet.read") a
// compile error instead of a silent denial.
//
// Derived from a census of every authorization check in the tree — see
// docs/rbac/permission-catalog.md for the mapping back to the code each key
// replaces, and docs/rbac/migration-risks.md for why the presets are shaped
// the way they are.
//
// Adding a permission: add it here, grant it in PRESET_ROLES if one of the
// built-in roles should hold it, and enforce it at the call site. Nothing is
// implied — there is no hierarchy and no wildcard. `admin` is not special to
// the checker; the Administrator preset simply holds nearly every key.

export type PermissionScope = "global" | "space" | "section";

/**
 * Principals other than a signed-in user that can hold a permission. These are
 * NOT grantable through roles — they belong to a kind of caller.
 *   anonymous — the public site and share links
 *   token     — API v1 / MCP bearer tokens (a ceiling on the owner's rights)
 *   scim      — the SCIM provisioner
 *   setup     — the first-run wizard, before any user exists
 *   lead      — group leadership (training team view; no admin bypass today)
 */
export type PermissionPrincipal = "anonymous" | "token" | "scim" | "setup" | "lead";

export interface Permission {
  key: string;
  label: string;
  description: string;
  scope: PermissionScope;
  /** Set when this is held by a non-user principal rather than by a role. */
  principal?: PermissionPrincipal;
}

export const PERMISSIONS = [
  // --- account ---
  { key: "account.connection_read", label: "List OAuth connections", description: "See connected OAuth/MCP clients", scope: "global" },
  { key: "account.connection_revoke", label: "Revoke OAuth connection", description: "Disconnect a client", scope: "global" },
  { key: "account.notification_prefs_manage", label: "Edit own notification settings", description: "Change notification preferences", scope: "global" },
  { key: "account.notification_prefs_read", label: "Read own notification settings", description: "View notification preferences", scope: "global" },
  { key: "account.password_change", label: "Change own password", description: "Set a new password", scope: "global" },
  { key: "account.preferences_manage", label: "Edit own preferences", description: "Theme, page width, timezone, date format", scope: "global" },
  { key: "account.profile_manage", label: "Edit own profile", description: "Name, email, avatar", scope: "global" },
  { key: "account.session_read", label: "List own sessions", description: "See active sessions", scope: "global" },
  { key: "account.session_revoke", label: "Revoke own sessions", description: "Sign other devices out", scope: "global" },
  { key: "account.token_create", label: "Mint API token", description: "Create a cdk_ personal access token", scope: "global" },
  { key: "account.token_read", label: "List own API tokens", description: "See personal access tokens", scope: "global" },
  { key: "account.token_revoke", label: "Revoke own API token", description: "Delete a personal access token", scope: "global" },
  { key: "account.twofa_manage", label: "Manage own 2FA", description: "Enrol/disable TOTP, view recovery codes", scope: "global" },
  // --- ai ---
  { key: "ai.proofread", label: "Use proofreader", description: "Run the AI proofreader", scope: "global" },
  { key: "ai.write_assist", label: "Use writing assistant", description: "Generate/rewrite prose in the editor", scope: "global" },
  // --- analytics ---
  { key: "analytics.document_read", label: "Read document analytics", description: "Per-document metrics", scope: "space" },
  { key: "analytics.read", label: "Read analytics", description: "Workspace analytics dashboard", scope: "global" },
  // --- announcement ---
  { key: "announcement.dismiss", label: "Dismiss announcement", description: "Dismiss for yourself", scope: "global" },
  { key: "announcement.manage", label: "Manage announcements", description: "Post/edit/expire org-wide announcements with email + chat delivery", scope: "section" },
  { key: "announcement.read", label: "Read announcements", description: "See announcements on the dashboard", scope: "global" },
  // --- api ---
  { key: "api.read", label: "API read scope", description: "Token may perform read operations on /api/v1", scope: "global", principal: "token" },
  { key: "api.write", label: "API write scope", description: "Token may perform mutations on /api/v1", scope: "global", principal: "token" },
  // --- attachment ---
  { key: "attachment.delete", label: "Delete attachment", description: "Remove an attachment", scope: "space" },
  { key: "attachment.read", label: "Download attachment", description: "Read a file attached to a document", scope: "space" },
  { key: "attachment.upload", label: "Upload attachment", description: "Attach a file to a document", scope: "space" },
  // --- audit ---
  { key: "audit.export", label: "Export audit log", description: "Download the audit trail", scope: "global" },
  { key: "audit.read", label: "Read audit log", description: "Browse the audit trail", scope: "global" },
  // --- change_request ---
  { key: "change_request.decide", label: "Approve/reject change", description: "Approve or reject a queued change request", scope: "space" },
  { key: "change_request.read", label: "Read review queue", description: "See pending change requests", scope: "space" },
  // --- comment ---
  { key: "comment.create", label: "Post comment", description: "Comment on a document", scope: "space" },
  { key: "comment.delete_any", label: "Moderate comments", description: "Delete any user's comment", scope: "space" },
  { key: "comment.delete_own", label: "Delete own comment", description: "Remove a comment you authored", scope: "space" },
  { key: "comment.read", label: "Read comments", description: "Read a document's comment thread", scope: "space" },
  // --- compliance ---
  { key: "compliance.export", label: "Export compliance evidence", description: "Download attestation evidence", scope: "section" },
  { key: "compliance.program_manage", label: "Run compliance program", description: "Issue requests, send reminders", scope: "section" },
  { key: "compliance.program_read", label: "Read compliance program", description: "Acknowledgement progress and outstanding requests", scope: "section" },
  // --- directory ---
  { key: "directory.field_manage", label: "Manage directory fields", description: "Define custom directory fields", scope: "global" },
  { key: "directory.person_manage", label: "Manage people", description: "Create/update/delete directory person records", scope: "global" },
  { key: "directory.photo_read", label: "Read directory photo", description: "Fetch a person's photo", scope: "global" },
  { key: "directory.print_columns_manage", label: "Manage print layout", description: "Configure directory print columns", scope: "global" },
  { key: "directory.read", label: "Read staff directory", description: "Browse the directory", scope: "global" },
  { key: "directory.search", label: "Search directory", description: "Search people", scope: "global" },
  { key: "directory.sync_manage", label: "Manage directory sync", description: "Configure Graph/directory synchronisation", scope: "global" },
  // --- document ---
  { key: "document.ack_require", label: "Require acknowledgement", description: "Toggle whether a document demands attestation", scope: "space" },
  { key: "document.ack_roster_read", label: "Read acknowledgement roster", description: "See who has and hasn't attested", scope: "space" },
  { key: "document.ack_submit", label: "Acknowledge policy", description: "Attest to having read a policy document", scope: "space" },
  { key: "document.branch", label: "Branch document", description: "Create a working copy", scope: "space" },
  { key: "document.create", label: "Create document", description: "Create a document in a space", scope: "space" },
  { key: "document.delete_draft", label: "Delete draft", description: "Move a draft to trash", scope: "space" },
  { key: "document.delete_published", label: "Delete published document", description: "Move a published document to trash", scope: "space" },
  { key: "document.dms_link_manage", label: "Manage DMS links", description: "Add/remove external DMS links", scope: "space" },
  { key: "document.dms_link_read", label: "Read DMS links", description: "List external DMS links on a document", scope: "space" },
  { key: "document.feedback_vote", label: "Vote helpfulness", description: "Cast/read your own 'was this helpful?' vote", scope: "space" },
  { key: "document.lookup", label: "Look up documents", description: "Query the link-insertion picker in the editor", scope: "space" },
  { key: "document.merge", label: "Merge branch", description: "Merge a working copy back to source", scope: "space" },
  { key: "document.move", label: "Move document", description: "Move a document between spaces", scope: "space" },
  { key: "document.presence", label: "Editing presence", description: "Publish/read the 'who else is editing' heartbeat", scope: "space" },
  { key: "document.publish", label: "Publish document", description: "Publish directly to live", scope: "space" },
  { key: "document.purge", label: "Purge permanently", description: "Irreversibly delete from trash", scope: "global" },
  { key: "document.read", label: "Read document", description: "Read a published document", scope: "space" },
  { key: "document.read_draft", label: "Read drafts", description: "See drafts and branch working copies in reads, search, trees, palette recents, relation pickers, tracking", scope: "space" },
  { key: "document.relation_manage", label: "Manage relations", description: "Add/remove document relations", scope: "space" },
  { key: "document.relation_read", label: "Read relations", description: "List related documents", scope: "space" },
  { key: "document.reorder", label: "Reorder pages", description: "Reorder sub-pages among siblings", scope: "space" },
  { key: "document.restore", label: "Restore from trash", description: "Restore a trashed document to its space", scope: "space" },
  { key: "document.review_manage", label: "Manage review schedule", description: "Set/clear the review date, mark reviewed", scope: "space" },
  { key: "document.schedule", label: "Schedule publish/expiry", description: "Set publish_at / archive_at", scope: "space" },
  { key: "document.share_create", label: "Create share link", description: "Mint an anonymous public link to a document", scope: "space" },
  { key: "document.share_read", label: "View share link", description: "Read a document's existing public share token", scope: "space" },
  { key: "document.share_revoke", label: "Revoke share link", description: "Invalidate a share token", scope: "space" },
  { key: "document.track_view", label: "Record a view", description: "Send a view-tracking ping", scope: "space" },
  { key: "document.update", label: "Edit document", description: "Edit title/body/metadata", scope: "space" },
  { key: "document.version_read", label: "Read version history", description: "View the version list and diffs", scope: "space" },
  { key: "document.version_restore", label: "Restore version", description: "Roll a document back to an earlier version", scope: "space" },
  // --- group ---
  { key: "group.create", label: "Create group", description: "Create a group", scope: "global" },
  { key: "group.delete", label: "Delete group", description: "Delete a group", scope: "global" },
  { key: "group.manage_members", label: "Manage group membership", description: "Add/remove members", scope: "global" },
  { key: "group.read", label: "Read groups", description: "List groups and members", scope: "global" },
  { key: "group.update", label: "Rename group", description: "Rename a group", scope: "global" },
  // --- identity ---
  { key: "identity.saml_manage", label: "Manage SAML", description: "Change identity-provider trust", scope: "global" },
  { key: "identity.saml_read", label: "Read SAML config", description: "View SAML settings", scope: "global" },
  { key: "identity.scim_manage", label: "Manage SCIM", description: "Change provisioning configuration", scope: "global" },
  { key: "identity.scim_provision", label: "Provision users (SCIM)", description: "Create/update/deprovision users and groups over SCIM", scope: "global", principal: "scim" },
  { key: "identity.scim_read", label: "Read SCIM config", description: "View provisioning configuration", scope: "global" },
  { key: "identity.scim_token_mint", label: "Mint SCIM token", description: "Issue a provisioning bearer token", scope: "global" },
  { key: "identity.sso_manage", label: "Manage SSO", description: "Change SSO settings", scope: "global" },
  { key: "identity.sso_read", label: "Read SSO settings", description: "View SSO settings", scope: "global" },
  // --- integration ---
  { key: "integration.addin_manifest_read", label: "Read add-in manifest", description: "Fetch the Office add-in manifest", scope: "global" },
  { key: "integration.ai_config_manage", label: "Manage AI config", description: "Change provider and API keys", scope: "global" },
  { key: "integration.ai_config_read", label: "Read AI config", description: "View AI provider configuration", scope: "global" },
  { key: "integration.backup_destination_manage", label: "Manage backup destinations", description: "Configure off-box backup targets", scope: "global" },
  { key: "integration.backup_destination_read", label: "Read backup destinations", description: "View configured backup targets", scope: "global" },
  { key: "integration.chat_ask_manage", label: "Manage chat integration", description: "Enable Slack/Teams ask and its signing secrets", scope: "global" },
  { key: "integration.chat_ask_read", label: "Read chat integration", description: "View Slack/Teams ask config", scope: "global" },
  { key: "integration.email_template_manage", label: "Manage email templates", description: "Edit/reset notification templates", scope: "global" },
  { key: "integration.email_template_read", label: "Read email templates", description: "View notification templates", scope: "global" },
  { key: "integration.email_test_send", label: "Send test email", description: "Send a template test message", scope: "global" },
  { key: "integration.embeddings_read", label: "Read index status", description: "Embedding index health", scope: "global" },
  { key: "integration.embeddings_reindex", label: "Trigger reindex", description: "Rebuild the embedding index", scope: "global" },
  { key: "integration.smtp_manage", label: "Manage SMTP config", description: "Change SMTP credentials (sealed secrets)", scope: "global" },
  { key: "integration.smtp_read", label: "Read SMTP config", description: "View mail transport settings", scope: "global" },
  { key: "integration.webhook_manage", label: "Manage webhooks", description: "Create/update/delete outbound webhooks", scope: "global" },
  { key: "integration.webhook_read", label: "Read webhooks", description: "List outbound webhooks", scope: "global" },
  // --- license ---
  { key: "license.install", label: "Install license", description: "Apply a license key — grants every EE entitlement", scope: "global" },
  { key: "license.read", label: "Read license", description: "View license state, seats, expiry", scope: "global" },
  // --- link ---
  { key: "link.category_manage", label: "Manage link categories", description: "Create/rename/delete link categories", scope: "global" },
  { key: "link.favicon_fetch", label: "Fetch remote favicon", description: "Fetch a remote favicon for previews", scope: "global" },
  { key: "link.icon_read", label: "Read link icon", description: "Fetch a link's cached icon", scope: "global" },
  { key: "link.manage", label: "Manage quick links", description: "Create/update/delete quick links and their group restrictions", scope: "global" },
  { key: "link.read", label: "Read quick links", description: "See quick links", scope: "global" },
  // --- mcp ---
  { key: "mcp.connect", label: "Connect MCP client", description: "Use the MCP tool surface with an OAuth access token", scope: "global", principal: "token" },
  // --- newsletter ---
  { key: "newsletter.asset_upload", label: "Upload newsletter image", description: "Upload an image asset", scope: "global" },
  { key: "newsletter.comment", label: "Comment on newsletter", description: "Post editorial comments", scope: "global" },
  { key: "newsletter.configure", label: "Configure newsletter", description: "Senders, appearance, recipient people list", scope: "global" },
  { key: "newsletter.create", label: "Create newsletter", description: "Start a newsletter draft", scope: "global" },
  { key: "newsletter.decide", label: "Approve / request changes", description: "Rule on a newsletter in review", scope: "global" },
  { key: "newsletter.delete", label: "Delete newsletter", description: "Delete a newsletter", scope: "global" },
  { key: "newsletter.dismiss", label: "Dismiss newsletter", description: "Dismiss a sent newsletter from your dashboard", scope: "global" },
  { key: "newsletter.edit_content", label: "Edit newsletter", description: "Edit subject/body", scope: "global" },
  { key: "newsletter.file_manage", label: "Manage newsletter files", description: "Attach/delete newsletter files", scope: "global" },
  { key: "newsletter.file_read", label: "Download newsletter file", description: "Download an attached file", scope: "global" },
  { key: "newsletter.manage_approvers", label: "Set approver override", description: "Change a newsletter's approver allow-list", scope: "global" },
  { key: "newsletter.read", label: "Read newsletter", description: "View a newsletter's detail and files", scope: "global" },
  { key: "newsletter.read_all", label: "Read all in-flight newsletters", description: "See other people's unsent drafts", scope: "global" },
  { key: "newsletter.schedule", label: "Schedule send", description: "Schedule an approved newsletter", scope: "global" },
  { key: "newsletter.send", label: "Send newsletter", description: "Send to the whole organization", scope: "global" },
  { key: "newsletter.send_test", label: "Send test copy", description: "Send a test to yourself", scope: "global" },
  { key: "newsletter.submit", label: "Submit for review", description: "Move a draft into review", scope: "global" },
  { key: "newsletter.use", label: "Use newsletter", description: "Access the newsletter module at all", scope: "global" },
  // --- notification ---
  { key: "notification.mark_read", label: "Mark notifications read", description: "Clear your unread badge", scope: "global" },
  { key: "notification.read", label: "Read notifications", description: "Read your notification feed", scope: "global" },
  // --- public ---
  { key: "public.attachment_read", label: "Read public attachment", description: "Anonymous attachment download via the public site", scope: "space", principal: "anonymous" },
  { key: "public.diagram_render", label: "Render diagram", description: "Anonymous PlantUML render", scope: "global", principal: "anonymous" },
  { key: "public.document_read", label: "Read public document", description: "Anonymous read of a published doc in a public space", scope: "space", principal: "anonymous" },
  { key: "public.indexing", label: "Allow search indexing", description: "Permit crawlers to index the public site", scope: "global", principal: "anonymous" },
  { key: "public.search", label: "Search public site", description: "Anonymous search", scope: "global", principal: "anonymous" },
  { key: "public.share_attachment_read", label: "Read shared attachment", description: "Anonymous attachment read scoped to exactly the shared document", scope: "global", principal: "anonymous" },
  { key: "public.share_read", label: "Read shared document", description: "Anonymous read of one document via a /share/<token> link", scope: "global", principal: "anonymous" },
  // --- role ---
  // Administering the permission model is itself a permission, so a workspace
  // can delegate (say) "assign roles" to an IT lead without also handing over
  // the ability to invent new ones.
  { key: "role.assign", label: "Assign roles", description: "Bind a role to a person or group, globally or in one space", scope: "global" },
  { key: "role.manage", label: "Manage roles", description: "Create, edit, and delete custom roles and their permissions", scope: "global" },
  { key: "role.read", label: "Read roles", description: "View roles, their permissions, and who holds them", scope: "global" },
  // --- search ---
  { key: "search.ai_query", label: "Ask AI", description: "Ask a grounded natural-language question", scope: "global" },
  { key: "search.public_query", label: "Public search", description: "Anonymous search of the public site", scope: "global", principal: "anonymous" },
  { key: "search.query", label: "Search", description: "Full-text/hybrid search", scope: "global" },
  // --- space ---
  { key: "space.author", label: "Author in space", description: "Create/edit/move/trash/attach within a space", scope: "space" },
  { key: "space.category_manage", label: "Manage space categories", description: "Create/rename/delete space categories", scope: "global" },
  { key: "space.category_read", label: "Read space categories", description: "List a space's categories", scope: "global" },
  { key: "space.create", label: "Create space", description: "Create a new space", scope: "global" },
  { key: "space.delete", label: "Delete space", description: "Delete a space and its contents", scope: "global" },
  { key: "space.edit_policy_manage", label: "Set org edit policy", description: "Toggle editors_edit_all — whether any editor may author anywhere", scope: "global" },
  { key: "space.manage_members", label: "Manage space access", description: "Grant/revoke the viewer groups and editor users/groups on a space", scope: "global" },
  { key: "space.read", label: "Read space", description: "See a space and its contents", scope: "space" },
  { key: "space.subscribe", label: "Subscribe to space", description: "Subscribe yourself to a space's change notifications", scope: "space" },
  { key: "space.tree_read", label: "Read page tree", description: "Read a space's page hierarchy", scope: "space" },
  { key: "space.update", label: "Update space", description: "Rename a space, change its visibility", scope: "global" },
  // --- status ---
  { key: "status.incident_manage", label: "Manage incidents", description: "Declare, update, resolve incidents (notifies the workspace)", scope: "global" },
  { key: "status.read", label: "Read status board", description: "View service status and incidents", scope: "global" },
  { key: "status.service_manage", label: "Manage monitored systems", description: "Add/remove monitored services", scope: "global" },
  // --- suggestion ---
  { key: "suggestion.create", label: "Suggest an edit", description: "Submit an inline suggestion as a reader", scope: "space" },
  { key: "suggestion.review", label: "Review suggestions", description: "Accept or dismiss reader suggestions", scope: "space" },
  // --- system ---
  { key: "system.backup_create", label: "Create backup", description: "Take a backup", scope: "global" },
  { key: "system.backup_delete", label: "Delete backup", description: "Remove a backup", scope: "global" },
  { key: "system.backup_download", label: "Download backup", description: "Download a backup archive", scope: "global" },
  { key: "system.backup_read", label: "List backups", description: "Enumerate backups", scope: "global" },
  { key: "system.backup_restore", label: "Restore backup", description: "Restore the workspace from a backup", scope: "global" },
  { key: "system.bootstrap", label: "First-run setup", description: "Create the initial admin account", scope: "global", principal: "setup" },
  { key: "system.diagnostics_read", label: "Read diagnostics", description: "Instance diagnostics", scope: "global" },
  { key: "system.export", label: "Export workspace", description: "Full workspace export", scope: "global" },
  { key: "system.import", label: "Import workspace", description: "Import content into the workspace", scope: "global" },
  { key: "system.migrate_run", label: "Run migration", description: "Execute a data migration", scope: "global" },
  { key: "system.update_apply", label: "Apply update", description: "Trigger an in-place upgrade", scope: "global" },
  { key: "system.version_read", label: "Read version", description: "Build/version info", scope: "global" },
  // --- template ---
  { key: "template.manage", label: "Manage templates", description: "Create/update/delete document templates", scope: "global" },
  { key: "template.read", label: "Use templates", description: "List document templates while authoring", scope: "global" },
  // --- training ---
  { key: "training.archive_read", label: "Read archived training", description: "Archived assignments/decks", scope: "section" },
  { key: "training.assignment_manage", label: "Manage assignments", description: "Assign, waive, reassign training", scope: "section" },
  { key: "training.audit_package_export", label: "Export audit package", description: "Produce the evidence bundle", scope: "section" },
  { key: "training.certificate_read_any", label: "Read any certificate", description: "View anyone's certificate", scope: "section" },
  { key: "training.certificate_read_own", label: "Read own certificate", description: "View your completion certificate", scope: "global" },
  { key: "training.deck_manage", label: "Manage training decks", description: "Create/update/delete decks", scope: "section" },
  { key: "training.deck_preview", label: "Preview a deck", description: "Preview deck content before assigning", scope: "section" },
  { key: "training.deck_read", label: "Read training decks", description: "List decks", scope: "section" },
  { key: "training.lead_manage", label: "Manage group leads", description: "Assign/remove group leads", scope: "section" },
  { key: "training.lead_read", label: "Read group leads", description: "See the group-lead roster", scope: "section" },
  { key: "training.matrix_read", label: "Read coverage matrix", description: "People × deck coverage grid", scope: "section" },
  { key: "training.overview_read", label: "Read training overview", description: "Org-wide completion dashboard", scope: "section" },
  { key: "training.person_read", label: "Read a person's record", description: "One person's full training record", scope: "section" },
  { key: "training.program_manage", label: "Manage training programs", description: "Create/update/delete programs", scope: "section" },
  { key: "training.progress_own", label: "Record own progress", description: "Advance/complete your own assignment", scope: "global" },
  { key: "training.read_own", label: "Read own training", description: "See your own assignments", scope: "global" },
  { key: "training.report_export", label: "Export training report", description: "Generate/download a report", scope: "section" },
  { key: "training.report_read", label: "Read training report", description: "View a compliance report", scope: "section" },
  { key: "training.snapshot_create", label: "Create snapshot", description: "Freeze a compliance snapshot", scope: "section" },
  { key: "training.snapshot_delete", label: "Delete snapshot", description: "Remove a snapshot", scope: "section" },
  { key: "training.snapshot_read", label: "Read snapshots", description: "List compliance snapshots", scope: "section" },
  { key: "training.team_read", label: "Read team training", description: "See training status for groups you lead", scope: "global", principal: "lead" },
  // --- ui ---
  { key: "ui.command_palette", label: "Use command palette", description: "Bootstrap the palette with recents and the server-computed allowed-command list", scope: "global" },
  // --- user ---
  { key: "user.create", label: "Create user", description: "Create an account", scope: "global" },
  { key: "user.delete", label: "Delete a user", description: "Delete an account", scope: "global" },
  { key: "user.link_directory", label: "Link to directory person", description: "Bind a user account to a directory record", scope: "global" },
  { key: "user.mention_list", label: "List mentionable users", description: "Read the @-mention candidate list", scope: "global" },
  { key: "user.read", label: "Read users", description: "List user accounts", scope: "global" },
  { key: "user.reset_password", label: "Reset a password", description: "Force-reset another user's password and invalidate sessions", scope: "global" },
  { key: "user.update_role", label: "Change a user's role", description: "Assign viewer/editor/approver/admin", scope: "global" },
  { key: "user.update_status", label: "Enable/disable a user", description: "Activate or disable an account", scope: "global" },
  // --- workspace ---
  { key: "workspace.branding_manage", label: "Manage branding", description: "Upload/remove the workspace logo", scope: "global" },
  { key: "workspace.domain_manage", label: "Manage custom domain", description: "Set the custom domain (drives TLS provisioning)", scope: "global" },
  { key: "workspace.public_site_manage", label: "Manage public site", description: "Enable/configure anonymous public access and indexing", scope: "global" },
  { key: "workspace.section_access_manage", label: "Manage section delegation", description: "Grant/revoke Announcements, Compliance, Training delegation", scope: "global" },
  { key: "workspace.settings_manage", label: "Change workspace settings", description: "Approval mode, session timeout, nested pages, secure-cookie mode", scope: "global" },
  { key: "workspace.settings_read", label: "Read workspace settings", description: "Read the settings surface", scope: "global" },
] as const satisfies readonly Permission[];

/** Every valid permission key, as a literal union. Typos stop compiling. */
export type PermissionKey = (typeof PERMISSIONS)[number]["key"];

const BY_KEY = new Map(PERMISSIONS.map((p) => [p.key as PermissionKey, p]));
export function permission(key: PermissionKey): Permission { return BY_KEY.get(key)!; }
export function isPermissionKey(v: string): v is PermissionKey { return BY_KEY.has(v as PermissionKey); }

/**
 * The four built-in roles, reproducing the pre-RBAC ladder EXACTLY so that
 * upgrading changes nobody's access. Each list is the set of permissions that
 * role satisfied under the old `roleAtLeast` checks, including the ones it got
 * transitively — the ladder is gone, so every key is spelled out.
 *
 * Administrator does not hold quite everything: training.team_read is granted
 * only by group leadership and never had an admin bypass, and the anonymous,
 * token, SCIM and setup permissions belong to other principals entirely.
 */
export const PRESET_ROLES = {
  viewer: {
    label: "Viewer",
    description: "Read documents and submit suggestions.",
    permissions: [
      "account.connection_read",
      "account.connection_revoke",
      "account.notification_prefs_manage",
      "account.notification_prefs_read",
      "account.password_change",
      "account.preferences_manage",
      "account.profile_manage",
      "account.session_read",
      "account.session_revoke",
      "account.token_create",
      "account.token_read",
      "account.token_revoke",
      "account.twofa_manage",
      "announcement.dismiss",
      "announcement.read",
      "attachment.read",
      "comment.create",
      "comment.delete_own",
      "comment.read",
      "directory.photo_read",
      "directory.read",
      "directory.search",
      "document.ack_submit",
      "document.dms_link_read",
      "document.feedback_vote",
      "document.read",
      "document.relation_read",
      "document.track_view",
      "link.favicon_fetch",
      "link.icon_read",
      "link.read",
      "newsletter.dismiss",
      "notification.mark_read",
      "notification.read",
      "search.ai_query",
      "search.query",
      "space.read",
      "space.subscribe",
      "space.tree_read",
      "status.read",
      "suggestion.create",
      "training.certificate_read_own",
      "training.progress_own",
      "training.read_own",
      "ui.command_palette",
      "user.mention_list",
    ] as PermissionKey[],
  },
  editor: {
    label: "Editor",
    description: "Create and edit documents. Changes to live docs go through review.",
    permissions: [
      "account.connection_read",
      "account.connection_revoke",
      "account.notification_prefs_manage",
      "account.notification_prefs_read",
      "account.password_change",
      "account.preferences_manage",
      "account.profile_manage",
      "account.session_read",
      "account.session_revoke",
      "account.token_create",
      "account.token_read",
      "account.token_revoke",
      "account.twofa_manage",
      "ai.proofread",
      "ai.write_assist",
      "announcement.dismiss",
      "announcement.read",
      "attachment.delete",
      "attachment.read",
      "attachment.upload",
      "comment.create",
      "comment.delete_own",
      "comment.read",
      "directory.photo_read",
      "directory.read",
      "directory.search",
      "document.ack_submit",
      "document.branch",
      "document.create",
      "document.delete_draft",
      "document.dms_link_manage",
      "document.dms_link_read",
      "document.feedback_vote",
      "document.lookup",
      "document.merge",
      "document.move",
      "document.presence",
      "document.read",
      "document.read_draft",
      "document.relation_manage",
      "document.relation_read",
      "document.reorder",
      "document.restore",
      "document.review_manage",
      "document.share_create",
      "document.share_read",
      "document.share_revoke",
      "document.track_view",
      "document.update",
      "document.version_read",
      "document.version_restore",
      "link.favicon_fetch",
      "link.icon_read",
      "link.read",
      "newsletter.dismiss",
      "notification.mark_read",
      "notification.read",
      "search.ai_query",
      "search.query",
      "space.author",
      "space.read",
      "space.subscribe",
      "space.tree_read",
      "status.read",
      "suggestion.create",
      "template.read",
      "training.certificate_read_own",
      "training.progress_own",
      "training.read_own",
      "ui.command_palette",
      "user.mention_list",
    ] as PermissionKey[],
  },
  approver: {
    label: "Approver",
    description: "Everything editors do, plus publish and review the queue.",
    permissions: [
      "account.connection_read",
      "account.connection_revoke",
      "account.notification_prefs_manage",
      "account.notification_prefs_read",
      "account.password_change",
      "account.preferences_manage",
      "account.profile_manage",
      "account.session_read",
      "account.session_revoke",
      "account.token_create",
      "account.token_read",
      "account.token_revoke",
      "account.twofa_manage",
      "ai.proofread",
      "ai.write_assist",
      "analytics.document_read",
      "analytics.read",
      "announcement.dismiss",
      "announcement.read",
      "attachment.delete",
      "attachment.read",
      "attachment.upload",
      "change_request.decide",
      "change_request.read",
      "comment.create",
      "comment.delete_own",
      "comment.read",
      "directory.photo_read",
      "directory.read",
      "directory.search",
      "document.ack_require",
      "document.ack_roster_read",
      "document.ack_submit",
      "document.branch",
      "document.create",
      "document.delete_draft",
      "document.delete_published",
      "document.dms_link_manage",
      "document.dms_link_read",
      "document.feedback_vote",
      "document.lookup",
      "document.merge",
      "document.move",
      "document.presence",
      "document.publish",
      "document.read",
      "document.read_draft",
      "document.relation_manage",
      "document.relation_read",
      "document.reorder",
      "document.restore",
      "document.review_manage",
      "document.schedule",
      "document.share_create",
      "document.share_read",
      "document.share_revoke",
      "document.track_view",
      "document.update",
      "document.version_read",
      "document.version_restore",
      "link.favicon_fetch",
      "link.icon_read",
      "link.read",
      "newsletter.dismiss",
      "notification.mark_read",
      "notification.read",
      "search.ai_query",
      "search.query",
      "space.author",
      "space.read",
      "space.subscribe",
      "space.tree_read",
      "status.incident_manage",
      "status.read",
      "suggestion.create",
      "suggestion.review",
      "template.read",
      "training.certificate_read_own",
      "training.progress_own",
      "training.read_own",
      "ui.command_palette",
      "user.mention_list",
    ] as PermissionKey[],
  },
  admin: {
    label: "Administrator",
    description: "Full control, including managing users and settings.",
    permissions: [
      "account.connection_read",
      "account.connection_revoke",
      "account.notification_prefs_manage",
      "account.notification_prefs_read",
      "account.password_change",
      "account.preferences_manage",
      "account.profile_manage",
      "account.session_read",
      "account.session_revoke",
      "account.token_create",
      "account.token_read",
      "account.token_revoke",
      "account.twofa_manage",
      "ai.proofread",
      "ai.write_assist",
      "analytics.document_read",
      "analytics.read",
      "announcement.dismiss",
      "announcement.manage",
      "announcement.read",
      "attachment.delete",
      "attachment.read",
      "attachment.upload",
      "audit.export",
      "audit.read",
      "change_request.decide",
      "change_request.read",
      "comment.create",
      "comment.delete_any",
      "comment.delete_own",
      "comment.read",
      "compliance.export",
      "compliance.program_manage",
      "compliance.program_read",
      "directory.field_manage",
      "directory.person_manage",
      "directory.photo_read",
      "directory.print_columns_manage",
      "directory.read",
      "directory.search",
      "directory.sync_manage",
      "document.ack_require",
      "document.ack_roster_read",
      "document.ack_submit",
      "document.branch",
      "document.create",
      "document.delete_draft",
      "document.delete_published",
      "document.dms_link_manage",
      "document.dms_link_read",
      "document.feedback_vote",
      "document.lookup",
      "document.merge",
      "document.move",
      "document.presence",
      "document.publish",
      "document.purge",
      "document.read",
      "document.read_draft",
      "document.relation_manage",
      "document.relation_read",
      "document.reorder",
      "document.restore",
      "document.review_manage",
      "document.schedule",
      "document.share_create",
      "document.share_read",
      "document.share_revoke",
      "document.track_view",
      "document.update",
      "document.version_read",
      "document.version_restore",
      "group.create",
      "group.delete",
      "group.manage_members",
      "group.read",
      "group.update",
      "identity.saml_manage",
      "identity.saml_read",
      "identity.scim_manage",
      "identity.scim_read",
      "identity.scim_token_mint",
      "identity.sso_manage",
      "identity.sso_read",
      "integration.addin_manifest_read",
      "integration.ai_config_manage",
      "integration.ai_config_read",
      "integration.backup_destination_manage",
      "integration.backup_destination_read",
      "integration.chat_ask_manage",
      "integration.chat_ask_read",
      "integration.email_template_manage",
      "integration.email_template_read",
      "integration.email_test_send",
      "integration.embeddings_read",
      "integration.embeddings_reindex",
      "integration.smtp_manage",
      "integration.smtp_read",
      "integration.webhook_manage",
      "integration.webhook_read",
      "license.install",
      "license.read",
      "link.category_manage",
      "link.favicon_fetch",
      "link.icon_read",
      "link.manage",
      "link.read",
      "newsletter.asset_upload",
      "newsletter.comment",
      "newsletter.configure",
      "newsletter.create",
      "newsletter.decide",
      "newsletter.delete",
      "newsletter.dismiss",
      "newsletter.edit_content",
      "newsletter.file_manage",
      "newsletter.file_read",
      "newsletter.manage_approvers",
      "newsletter.read",
      "newsletter.read_all",
      "newsletter.schedule",
      "newsletter.send",
      "newsletter.send_test",
      "newsletter.submit",
      "newsletter.use",
      "notification.mark_read",
      "notification.read",
      "role.assign",
      "role.manage",
      "role.read",
      "search.ai_query",
      "search.query",
      "space.author",
      "space.category_manage",
      "space.category_read",
      "space.create",
      "space.delete",
      "space.edit_policy_manage",
      "space.manage_members",
      "space.read",
      "space.subscribe",
      "space.tree_read",
      "space.update",
      "status.incident_manage",
      "status.read",
      "status.service_manage",
      "suggestion.create",
      "suggestion.review",
      "system.backup_create",
      "system.backup_delete",
      "system.backup_download",
      "system.backup_read",
      "system.backup_restore",
      "system.diagnostics_read",
      "system.export",
      "system.import",
      "system.migrate_run",
      "system.update_apply",
      "system.version_read",
      "template.manage",
      "template.read",
      "training.archive_read",
      "training.assignment_manage",
      "training.audit_package_export",
      "training.certificate_read_any",
      "training.certificate_read_own",
      "training.deck_manage",
      "training.deck_preview",
      "training.deck_read",
      "training.lead_manage",
      "training.lead_read",
      "training.matrix_read",
      "training.overview_read",
      "training.person_read",
      "training.program_manage",
      "training.progress_own",
      "training.read_own",
      "training.report_export",
      "training.report_read",
      "training.snapshot_create",
      "training.snapshot_delete",
      "training.snapshot_read",
      "ui.command_palette",
      "user.create",
      "user.delete",
      "user.link_directory",
      "user.mention_list",
      "user.read",
      "user.reset_password",
      "user.update_role",
      "user.update_status",
      "workspace.branding_manage",
      "workspace.domain_manage",
      "workspace.public_site_manage",
      "workspace.section_access_manage",
      "workspace.settings_manage",
      "workspace.settings_read",
    ] as PermissionKey[],
  },
} as const;

export type PresetRoleKey = keyof typeof PRESET_ROLES;
export const PRESET_ROLE_KEYS = Object.keys(PRESET_ROLES) as PresetRoleKey[];
